### ISSUE TITLE
Repeated (Identical) Types in Implementing Libraries 

### ISSUE THREAD

**Issue by Gastove** [fsprojects/FSharp.Formatting#647] opened 2021-03-05 04:34 UTC
I've been working with the folk over at Fleece on some documentation updates. This has involved, among other things, updating quite a number of major versions of `FSharp.Formatting`. 

On `FSharp.Formatting` 9.0.1, we're seeing a [great number of repeat types](https://wallymathieu.github.io/Fleece/reference/fleece.html). Fleece is structured as a base module that is then used in JSON-framework-specific implementations; it appears we're getting one copy of each type from the base module, then a repeat of each type for each specific implementation. 

How can we reduce this down, filter out the duplicates? 

Thanks very much!

**Comment by dsyme** [comment] 2021-03-24 00:14
Hmmmmm I'm not at all sure.  Could you create some kind of minimal repro?  The relevant code will be GenerateModel.fs

**Comment by dsyme** [comment] 2021-03-24 00:16
> Fleece is structured as a base module that is then used in JSON-framework-specific implementations; it appears we're getting one copy of each type from the base module, then a repeat of each type for each specific implementation.

Could you add links pointing to the specific source lines for the constructs you think are causing the duplication?

**Comment by dsyme** [comment] 2021-03-24 00:37
To be honest I'd recommend generous use of `exclude` tags https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1031-xmldoc-extensions.md#exclude

There are multiple types of the same name in the same namespace across multiple DLLs.  They should either be internal or, if really desired (which is incredibly rare), they should be explicitly excluded.

**Comment by dsyme** [comment] 2021-03-24 00:38
(Closed as this is really by design for this this rare case - arguably showing the multiple types highlights a potential bug)

**Closed by dsyme** 2021-03-24 00:37 UTC
