### ISSUE TITLE
Can't generate documentation on Linux: "Failed to import assembly 'Argu, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by rmunn** [fsprojects/FSharp.Formatting#412] opened 2016-06-29 05:56 UTC
There seems to be a problem running FSharp.Formatting's `generate.fsx` script on Linux. I have consistently been able to reproduce the same results: the first run will succeed. (Well, sort of -- there's another bug that's being triggered, but see below for details). Then the second run will fail with an error about "Failed to import assembly Argu", and that's the bug that I'm trying to report right now.

The first clue that the "Failed to import assembly Argu" error is going to show up is if, when running `./build.sh GenerateDocs`, the compilation output includes the line:

> Redirect assembly from 'FSharp.Compiler.Service, Version=2.0.0.3, Culture=neutral, PublicKeyToken=null' to 'FSharp.Compiler.Service, Version=2.0.0.6, Culture=neutral, PublicKeyToken=null'

If this assembly redirect appears, it will soon be followed by:

> Compilation errors:
> - error: (0, 0) Unhandled Exception:
> - error: (0, 0) Mono.CSharp.InternalErrorException: Failed to import assembly `Argu, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' ---> System.ArgumentException: Value does not fall within the expected range.
> - error: (0, 0)   at IKVM.Reflection.Fusion.CompareAssemblyIdentityPure (System.String assemblyIdentity1, Boolean unified1, System.String assemblyIdentity2, Boolean unified2, IKVM.Reflection.AssemblyComparisonResult& result) <0x7f23f8ead540 + 0x00c43> in <filename unknown>:0 
> - error: (0, 0)   at IKVM.Reflection.Universe.CompareAssemblyIdentity (System.String assemblyIdentity1, Boolean unified1, System.String assemblyIdentity2, Boolean unified2, IKVM.Reflection.AssemblyComparisonResult& result) <0x7f23f8ed66a0 + 0x0006e> in <filename unknown>:0 
> - error: (0, 0)   at Mono.CSharp.StaticLoader.AssemblyReferenceResolver (System.Object sender, IKVM.Reflection.ResolveEventArgs args) <0x7f23f8e1ab80 + 0x0010d> in <filename unknown>:0 
> - error: (0, 0)   at IKVM.Reflection.Universe.Load (System.String refname, IKVM.Reflection.Module requestingModule, Boolean throwOnError) <0x7f23f8ed5ba0 + 0x0010a> in <filename unknown>:0 

(snip the rest of the stacktrace, as it contains no line numbers and will probably not be useful. I can post the whole thing if it would help.)
### Steps to reproduce
1. Get an Ubuntu Trusty (14.04) or Linux Mint 18 (based on Ubuntu Xenial 16.04) machine, and install the latest version of Mono (4.4.1) by following the instructions at http://www.mono-project.com/docs/getting-started/install/linux/
2. `git clone https://github.com/tpetricek/FSharp.Formatting`
3. `cd FSharp.Formatting`
4. `./build.sh` - NOTE: On some systems, this seems to trigger fsharp/FAKE#1196. I believe that bug is unrelated to the one I'm reporting now -- but the source of that encoding mismatch also needs to be tracked down.
5. `./build.sh GenerateDocs` - will **fail** with a `Mono.CSharp.InternalErrorException`.
6. `rm -rf docs/tools/.fake && ./build.sh GenerateDocs` will "succeed". (Sort of -- right now it triggers fsharp/FAKE#1196, but it bypasses the "Failed to import assembly Argu" error that this bug report is about).

Clearly, the cached build script that FAKE produces has an assembly reference to FSharp.Compiler.Service 2.0.0.3, but its current version (which Paket downloads) is 2.0.0.6. Somehow, this is triggering a bug in Mono's assembly resolver that makes it unable to load Argu, and things blow up.

I believe the FSharp.Compiler.Service 2.0.0.3 reference is coming from FSharpVSPowerTools, because I see the following in `paket.lock` after building FSharp.Formatting:

```
FSharpVSPowerTools.Core (2.3)
  FSharp.Compiler.Service (>= 2.0.0.3)
```

However, I've been unable to trace this bug any further. I don't know why the assembly redirect is triggering a failure on importing Argu. All I know is that FSharp.Formatting's `generate.fsx` script seems to be at the heart of this bug.
### Miscellaneous notes

I've actually been seeing this bug for some time, before I ever saw fsharp/FAKE#1196 being triggered. The way I used to see it was to check out a clean copy of https://github.com/fsprojects/ProjectScaffold, run its `./build.sh` once to give the project a name, then try to run `./build.sh GenerateHelp` twice. The first run would succeed, and the second one would fail with this bug. However, if I do that now, the first run triggers fsharp/FAKE#1196 and then the second one triggers this bug.

**Comment by matthid** [comment] 2016-06-29 07:06
Best way to get this fixed is to reproduce this in a standalone app (use codedom compiler) and report it to mono. I would assume it's a mono bug.

**Comment by rmunn** [comment] 2016-06-29 07:57
I'm afraid I'm relatively new to .NET coding, and would have a great deal of difficulty narrowing this bug down to something standalone that could be reported to Mono. If I try to do that, this bug is going to sit open for months. I've tried to give enough information in this bug report so that someone more experienced could reproduce it consistently -- and then, with greater experience, perhaps be able to narrow it down much more quickly than I could.

**Comment by matthid** [comment] 2016-06-29 08:33
That's fine. Somebody (probably me) will do that eventually. Just quickly wanted to add that it is a mono bug and you could downgrade mono for example as a quick solution...

**Comment by rmunn** [comment] 2016-06-29 09:25
If it really is a mono bug, it's one that has been around a long time: I followed the instructions at http://stackoverflow.com/questions/30109928/rollback-mono-4-0-1-to-3-12-0 to downgrade Mono to 4.2, then 4.0, then 3.12 -- and every time, I still had the same "Failed to import assembly Argu" error. (I checked by using the simpler repro method of checking out a copy of ProjectScaffold. then trying "./build.sh GenerateHelp" twice -- the first run succeeds because there's no FAKE cache yet, but the second one uses the cached DLL that FAKE creates from the `generate.fsx` script, and that run produces the 2.0.0.3 -> 2.0.0.6 redirect and the "Failed to import assembly Argu" error.)

**Comment by matthid** [comment] 2016-06-29 11:51
Thanks for testing this.

**Comment by zaaack** [comment] 2017-09-17 13:03
Still here in Mono 5.2.0.224, macos

**Comment by wallymathieu** [comment] 2018-01-09 05:57
It seems to happen sometimes for me (on Mac OS X). I wonder if there is some tmp state that causes it?

**Comment by wallymathieu** [comment] 2018-02-05 06:28
It looks like this could be fixed in the beta of v3. After upgrading F#+ the doc generation seems more stable https://github.com/gusty/FSharpPlus/pull/79

**Comment by dsyme** [comment] 2019-04-12 23:11
Closing out old issue

**Closed by dsyme** 2019-04-12 23:11 UTC
