### ISSUE TITLE
Duplication between template.cshtml and template-project.html

### ISSUE THREAD

**Issue by AnthonyLloyd** [fsprojects/FSharp.Formatting#399] opened 2016-04-12 10:46 UTC
Hi, Is there a way to not have to duplicate the menu items between these if you have docs plus apidocs?

The following is an example from FAKE

https://github.com/fsharp/FAKE/blob/master/help/templates/template.cshtml
https://github.com/fsharp/FAKE/blob/master/help/literate/templates/template-project.html

**Comment by dsyme** [comment] 2020-07-09 00:46
There's currently no planned way within the templating provided by this repo to avoid this when multiple templates are used.  This is by design (or at least out of scope for this repo, which has suffered from overly complex templating and we're trying to keep it simple).

**Closed by dsyme** 2020-07-09 00:46 UTC
