### ISSUE TITLE
beta 11 not compatible with FAKE 5.0

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharp.Formatting#471] opened 2018-06-11 03:23 UTC
Conflict detected:
   - FSharp.Formatting 3.0.0-beta11 requested package FSharp.Compiler.Service: >= 22.0.3 < 23.0*
   - Fake.Runtime 5.0.0 requested package FSharp.Compiler.Service: >= 23.0.3

**Comment by matthid** [comment] 2018-06-11 04:12
The problem is that the package is not compatible with netstandard, and fake is now netcore only. So we need to port this library...

In the meantime you can use the command line tool of fsharp.formatting (for example look at fake repository)

**Comment by matthid** [comment] 2018-06-11 04:13
(What I’m saying is: even if we update the dependency or you would fallback to older fake packages it wouldn’t work)

**Comment by wallymathieu** [comment] 2018-06-11 08:27
What is needed in order to get FSharp.Formatting to be on netstandard?

**Comment by jackfoxy** [comment] 2018-06-11 21:44
Does this involve more than just a multi-targeted dotnet core SDK project?

**Comment by matthid** [comment] 2018-06-11 21:47
Updating the build to dotnet sdk is the first step yes, and then we will see what we need in order to function on netcore. I'd assume other issues will pop up along the way.

**Comment by jackfoxy** [comment] 2018-06-12 23:40
@matthid  I never saw this before for F#.Formatting beta11
I'm trying to put it in its own paket dependency group for the first time

````
Resolving packages for group Formatting:
 - FSharp.Formatting 3.0.0-beta11
Trial1 (NuGet.GetVersions) did not yield any results, trying again.
   https://ci.appveyor.com/nuget/fsharp-formatting/FindPackagesById()?semVerLevel=2.0.0&id='Microsoft.AspNet.Razor'
   https://ci.appveyor.com/nuget/fsharp-formatting/Packages?semVerLevel=2.0.0&$filter=Id eq 'Microsoft.AspNet.Razor'
Trial1 (NuGet.GetVersions) did not yield any results, trying again.
   https://ci.appveyor.com/nuget/fsharp-formatting/FindPackagesById()?semVerLevel=2.0.0&id='FSharp.Compiler.Service'
   https://ci.appveyor.com/nuget/fsharp-formatting/Packages?semVerLevel=2.0.0&$filter=Id eq 'FSharp.Compiler.Service'
Trial1 (NuGet.GetVersions) did not yield any results, trying again.
   https://ci.appveyor.com/nuget/fsharp-formatting/FindPackagesById()?semVerLevel=2.0.0&id='System.ValueTuple'
   https://ci.appveyor.com/nuget/fsharp-formatting/Packages?semVerLevel=2.0.0&$filter=Id eq 'System.ValueTuple'
````
 
````
Paket failed with
-> Unable to retrieve package versions for 'FSharp.Compiler.Service'
   -- CLOSED --
      FSharp.Formatting  (from E:\GitRepos\FsRegEx\paket.dependencies)
   -- OPEN ----
      FSharp.Compiler.Service >= 22.0.3 < 23.0 (from FSharp.Formatting 3.0.0-beta11)
      System.ValueTuple >= 4.4 < 5.0 (from FSharp.Formatting 3.0.0-beta11)
      Microsoft.AspNet.Razor >= 3.2.4 < 4.0 (from FSharp.Formatting 3.0.0-beta11)
-> Could not find versions for package FSharp.Compiler.Service on https://ci.appveyor.com/nuget/fsharp-formatting.
-> Source 'https://ci.appveyor.com/nuget/fsharp-formatting' yielded (0): []
        -  Request 'https://ci.appveyor.com/nuget/fsharp-formatting/FindPackagesById()?semVerLevel=2.0.0&id='FSharp.Compiler.Service'' finished with: []
        -  Request 'https://ci.appveyor.com/nuget/fsharp-formatting/Packages?semVerLevel=2.0.0&$filter=Id eq 'FSharp.Compiler.Service'' was cancelled (another one was faster)
````

**Comment by dsyme** [comment] 2019-04-12 23:06
Closing in favour of #455

**Closed by dsyme** 2019-04-12 23:06 UTC
